name: Check codestyle and run tests

on: [push, pull_request, workflow_dispatch]

jobs:
  code_checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements_dev.txt

      - name: Analysing the code with flake8
        run: |
          python -m flake8 .

      - name: Analysing the code with mypy
        run: |
          python -m mypy . --show-error-context

      - name: Running tests
        run: |
          python -m pytest -vv --cov --self-contained-html --html=test_report.html --cov-report=html

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test_reports
          path: |
            test_report.html
            htmlcov
